// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { getBankAccounts, getBills, getHealth, getIndex, type Options, postAgentChat, postBankAccounts, postBills, postBillsByIdPay } from '../sdk.gen';
import type { GetBankAccountsData, GetBillsData, GetHealthData, GetIndexData, PostAgentChatData, PostBankAccountsData, PostBillsByIdPayData, PostBillsData } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getIndexQueryKey = (options?: Options<GetIndexData>) => createQueryKey('getIndex', options);

export const getIndexOptions = (options?: Options<GetIndexData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getIndexQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getIndex({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getIndexQueryKey(options)
});

export const getHealthQueryKey = (options?: Options<GetHealthData>) => createQueryKey('getHealth', options);

export const getHealthOptions = (options?: Options<GetHealthData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getHealthQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getHealth({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getHealthQueryKey(options)
});

/**
 * Stream a chat response from Gemini
 */
export const postAgentChatMutation = (options?: Partial<Options<PostAgentChatData>>): UseMutationOptions<unknown, DefaultError, Options<PostAgentChatData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PostAgentChatData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postAgentChat({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getBankAccountsQueryKey = (options?: Options<GetBankAccountsData>) => createQueryKey('getBankAccounts', options);

/**
 * Get all bank accounts
 */
export const getBankAccountsOptions = (options?: Options<GetBankAccountsData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getBankAccountsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getBankAccounts({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getBankAccountsQueryKey(options)
});

/**
 * Create a new bank account
 */
export const postBankAccountsMutation = (options?: Partial<Options<PostBankAccountsData>>): UseMutationOptions<unknown, DefaultError, Options<PostBankAccountsData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PostBankAccountsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postBankAccounts({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getBillsQueryKey = (options?: Options<GetBillsData>) => createQueryKey('getBills', options);

/**
 * List all bills
 */
export const getBillsOptions = (options?: Options<GetBillsData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getBillsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getBills({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getBillsQueryKey(options)
});

/**
 * Create a new bill
 */
export const postBillsMutation = (options?: Partial<Options<PostBillsData>>): UseMutationOptions<unknown, DefaultError, Options<PostBillsData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PostBillsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postBills({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Pay a bill using a bank account
 *
 * Deducts the bill amount from the specified bank account and marks the bill as paid.
 */
export const postBillsByIdPayMutation = (options?: Partial<Options<PostBillsByIdPayData>>): UseMutationOptions<unknown, DefaultError, Options<PostBillsByIdPayData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PostBillsByIdPayData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postBillsByIdPay({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
